### ISSUE TITLE
Implement new user interface

### ISSUE THREAD

**Issue by victorfisac** [victorfisac/rPBR#1]
@raysan5 created a really nice and UX friendly mockup of a new user interface for rPBR. Here is a image reference:

![rpbr_mockup_01](https://user-images.githubusercontent.com/10688349/27949340-a162f670-62fd-11e7-8a77-2eacc8ec02cb.png)

**Comment by raysan5** [comment]
Hey @victorfisac! Still working on that! 

Actually, [SlideBars have been redesigned](https://raw.githubusercontent.com/raysan5/raygui/master/design/raygui_style_table_light_REV8.png) for better consistency and I'm planning to do some color tweaks; specially on [dark style](https://raw.githubusercontent.com/raysan5/raygui/master/design/raygui_style_table_dark_REV6.png).

PBR support is almost complete in raylib, just some more days... it requires lot of redesign!
